---
title: "02 Data Acqusition"
date: "2021-05"
output:
  html_document:
    toc: true
    toc_float: true
    df_print: paged
    collapsed: false
    number_sections: true
    toc_depth: 3
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE,warning=FALSE, cache=TRUE)
```


```{r}
library(jsonlite)
library(glue)
library(RSQLite)
library(httr)
library(xml2)
library(tidyverse)
library(tibble)  
library(readr)     
library(dplyr)    
library(magrittr) 
library(tidyr)    
library(stringr)
library(ggplot2)  

#shows the 7 days weather forecast in hamburg

resp <- GET("http://www.7timer.info/bin/api.pl?lon=53.55&lat=9.99&product=civillight&output=json")

weather_data<- resp %>% 
  .$content %>% 
  rawToChar() %>% 
  fromJSON()

forecast <- weather_data[[3]]
forecast
```

```{r}
 # WEBSCRAPING ----

# 1.0 LIBRARIES ----

library(tidyverse) # Main Package - Loads dplyr, purrr, etc.
library(rvest)     # HTML Hacking & Web Scraping
library(xopen)     # Quickly opening URLs
library(jsonlite)  # converts JSON files to R objects
library(glue)      # concatenate strings
library(stringi)   # character string/text processing
library(strex)
library(tibble)

            url  <- "https://www.rosebikes.de/fahrr%C3%A4der/mtb"
                      html <- url %>% 
                        read_html()
            name <- html  %>% 
                      html_nodes(".catalog-category-bikes__title-text") %>% 
                        html_text() %>% 
            gsub(pattern = '\\t|\\r|\\n', replacement = '')
            price <- html  %>% 
              html_nodes(".catalog-category-bikes__price-title") %>% 
              html_text() %>% 
              gsub(pattern = '\\t|\\r|\\n|', replacement = '') %>% 
              stringr::str_replace_all(pattern = "\\.",replacement = "")  %>% 
              stringr::str_replace_all(pattern = ",",replacement = "")  %>% 
              stringr::str_replace_all(pattern = "00",replacement = "") %>% 
              stringr::str_replace_all(pattern = "ab ",replacement = "")  %>% 
              stringr::str_replace_all(pattern = "€",replacement = "") %>%
              stringr::str_replace_all(pattern = "[[:space:]]",replacement = "") %>%
              # Extract numbers
              #stringr::str_remove(pattern = "[a-z]+")
              as.numeric()
          bike_tbl <- tibble(name,price)  
          bike_tbl
```            
         