---
title: "03 Data Wrangling"
date: "2021-05"
output:
  html_document:
    toc: true
    toc_float: true
    df_print: paged
    collapsed: false
    number_sections: true
    toc_depth: 3
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE,warning=FALSE, cache=TRUE)
```

```{r}
library(vroom)
library(dplyr)
library(tidyverse)
library(vroom)
library(data.table)
library(tictoc)

#patent
col_types <- list(
  id = col_character(),
  type = col_character(),
  number = col_character(),
  country = col_character(),
  date = col_date("%Y-%m-%d"),
  abstract = col_character(),
  title = col_character(),
  kind = col_character(),
  num_claims = col_double(),
  filename = col_character(),
  withdrawn = col_double()
)

patent_tbl <- vroom(
  file       = "patent.tsv", 
  delim      = "\t", 
  col_types  = col_types,
  na         = c("", "NA", "NULL")
)
#assignee
col_types_assignee <- list(
  id = col_character(),
  type = col_character(),
  name_first = col_character(),
  name_last = col_character(),
  organization = col_character()
)

assignee_tbl <- vroom(
  file       = "assignee.tsv", 
  delim      = "\t", 
  col_types  = col_types,
  na         = c("", "NA", "NULL")
)

col_types_patent_assignee <- list(
  patent_id = col_character(),
  assignee_id = col_character(),
  location_id = col_character()
)

patent_assignee_tbl <- vroom(
  file       = "patent_assignee.tsv", 
  delim      = "\t", 
  col_types  = col_types,
  na         = c("", "NA", "NULL")
)

col_types_uspc <- list(
  uuid = col_character(),
  patent_id = col_character(),
  mainclass_id = col_character(),
  subclass_id = col_character(),
  sequence = col_integer()
)

uspc_tbl <- vroom(
  file       = "uspc.tsv", 
  delim      = "\t", 
  col_types  = col_types_uspc,
  na         = c("", "NA", "NULL")
) 

setDT(patent_tbl)
setDT(assignee_tbl)
setDT(patent_assignee_tbl)
setDT(uspc_tbl)

# Which US company has the most patents?
setnames(assignee_tbl, "id", "assignee_id")
combined_data <- merge(x = patent_assignee_tbl, y = assignee_tbl, by = "assignee_id")
us_patents <- combined_data %>%
  filter(type == 2)%>%
  filter(!is.na(patent_id) || !is.na(organization)) %>%
  select(-type, -assignee_id)%>% 
  group_by(organization) %>%
  count(patent_id) %>%
  select(-patent_id)%>%
  summarise(total = sum(n))%>%
  arrange(desc(total))   
us_top_10 <- us_patents %>% slice(1:10)
us_top_10

##2

  
  tbl_2 <- patent_tbl %>%   
    separate(col  = date,
             into = c("year", "month", "day"),
             sep  = "-", remove = TRUE) %>%
    mutate(
      month = as.numeric(month)
    )%>%
    filter(month == 08)%>%
    select(-year, -day)
  setnames(tbl_2, "id", "patent_id")
  combined_data_2 <- merge(x = tbl_2, y = combined_data, by = "patent_id")
  us_top_10_2014 <- combined_data_2%>%
    filter(type == 2)%>%
    filter(!is.na(patent_id) || !is.na(organization)) %>%
    select(organization, patent_id) %>%
    group_by(organization) %>%
    count(patent_id) %>%   
    summarise(total_patents = sum(n))%>%
    arrange(desc(total_patents)) %>% slice(1:10)  
  us_top_10_2014
  us_top_10_2014_new <- combined_data_2%>%
    filter(type == 2 & num_claims == 1)%>%
    filter(!is.na(patent_id) || !is.na(organization)) %>%
    select(organization, patent_id) %>%
    group_by(organization) %>%
    count(patent_id) %>%   
    summarise(total_patents = sum(n))%>%
    arrange(desc(total_patents)) %>% slice(1:10)
  us_top_10_2014_new

  ##3 
  combined_data_3 <- merge(x = uspc_tbl, y = combined_data_2, by = "patent_id")
  top10_worlwide_patents <- combined_data_3  %>%
    filter(!is.na(patent_id) || !is.na(organization))%>%
    group_by(organization) %>%
    arrange(desc(mainclass_id)) %>%
    # set mainclass order first, the result will be sorted automatically 
    count(patent_id) %>%
    select(-patent_id)%>%
    summarise(total_patents_wordwide = sum(n))%>%
    ungroup() %>%
    arrange(desc(total_patents_wordwide)) %>% slice(1:10)  
  top10_worlwide_patents 
```
  