---
title: "04 Data Visualization"
date: "2021-05"
output:
  html_document:
    toc: true
    toc_float: true
    df_print: paged
    collapsed: false
    number_sections: true
    toc_depth: 3
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE,warning=FALSE, cache=TRUE)
```
# Challenge 4.1
This is the first part of the challenge where we plot the cumulative covid cases by country :  

```{r}
library(ggplot2)
library(tidyverse)
library(lubridate)
library(dplyr)
library(magrittr)
library(ggplot2)

covid_data_tbl <- read_csv("https://covid.ourworldindata.org/data/owid-covid-data.csv")

# 2. Data manipluation

covid_cases_tbl <- covid_data_tbl %>%
filter(location %in% c("Germany",
                         "United Kingdom",
                         "France",
                         "Spain",
                         "Algeria",
                         "United States"))
covid_cases_tbl
covid_cases_tbl %>%
  ggplot(aes(x=date, y=total_cases,
             group=location,
             colour=location))+
  geom_line()+
  scale_linetype_discrete(name="location") +
  xlab("Date") + 
  ylab("Total Cases") +
  scale_x_date(date_breaks = "1 month", date_labels =  "%b %Y") +
  scale_y_continuous(breaks=100000)+
  scale_y_continuous(labels = scales::number)+
  theme(axis.text.x=element_text(angle=45, hjust=1))+
  labs(
    title = "Corona virus total cases by country",
    fill = "location"
  )
```

# Challenge 4.2
A plot of the mortality rate of covid worldwide
```{r}
library(ggrepel)
library(RColorBrewer)
library(maps)
library(tidyverse)
library(lubridate)

#read the data
covid_data_tbl <- read_csv("https://covid.ourworldindata.org/data/owid-covid-data.csv")
world <- map_data ("world")

world[is.na(world)] <- 0  # set NA values to 0
# filter only needed data
covid_data <- covid_data_tbl %>% select(total_deaths, date, location, population)
#calculation of mortality rate
covid_data$mortality_rate = (covid_data_tbl$total_deaths/covid_data_tbl$population)*100 
covid_data[is.na(covid_data)] <- 0 # set NA values to 0
#choose the actual date, filter the data not needed anymore
covid_now<- covid_data %>% filter(date == Sys.Date()-1) %>%
  select(-population, -total_deaths, -date)%>% 
  rename(region = location)
covid_now[is.na(covid_now)] <- 0 #set NA values to 0
#change the names of the US, UK, and Congo regions    
   world$region[world$region == "UK"] <- "United Kingdom" 
   world$region[world$region == "US"] <- "United Stated" 
   world$region[world$region == "Democratic Republic of the Congo"] <- "Democratic Republic of Congo" 

#combine the data to the map      
map_data <- merge(x = world, y = covid_now, 
                             by    = "region", 
                             all.x = TRUE, 
                             all.y = FALSE) %>%
                 arrange(order)
map_data[is.na(map_data)] <- 0
#plot the worldmap
ggplot(map_data,aes(fill = mortality_rate)) + 
         geom_map(map=map_data, 
         aes(long, lat, map_id=region), 
         col="red")+
         expand_limits(x = world$long, y = world$lat) + 
         theme( axis.text.x=element_blank(),
                axis.text.y=element_blank()) +
labs(
  title = ("Mortality rate of COVID-19 Worldwide"),
  caption = Sys.Date(),
  x = "",
  y = "",
  fill = "Mortality Rate") +
  scale_fill_continuous(limits=c(0,0.255), breaks=c(0.05, 0.1, 0.15,0.2,0.25),
                        labels = c("0.050%", "0.100%", "0.150%","0.200%","0.250%"))
```